title: Course name (edit _config.yml)

description: > # this means to ignore newlines until "contact:"
  Computer Architecture at UiT, fall 2024.

contact:
  email: lars.ailo.bongo@uit.no
  name: Lars Ailo Bongo (edit _config.yml)

# you don't need to adapt the settings below
baseurl: ""
markdown: kramdown
